import SideBar from '@/components/SideBar'
import './globals.css'
import { SessionProvider } from "../components/SessionProvider";
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google'
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import Login from '@/components/Login';
import ClientProvider from '@/components/ClientProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions)

  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ): ( 
          <div className="flex">
            {/* sidebar (later stage) */}
            <div className="bg-[#18122B] max-w-xs h-screen 
            overflow-y-auto md:min-w-[20rem]">
              <SideBar />
            </div>

            {/* ClinetProvider - Notification */}
            <ClientProvider />

            <div className="bg-[#27374D] flex-1">{children}</div>
          </div>
          )}

        </SessionProvider>
      </body>
    </html>
  )
}
